@startuml

title Диаграмма контекста банка "Стандарт"

left to right direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(customer, "Клиент", "Клиент компании")
Person(backOfficeManager, "Менеджер бэк-офиса", "Сотрудник компании")
Person(frontOfficeManager, "Менеджер фронт-офиса", "Сотрудник компании")
Person(callCenterManager, "Менеджер кол-центра", "Сотрудник компании или партнерского кол-центра")

System(abs, "АБС", "Система, предназначенная для автоматизации банковских процессов")
System(onlineBank, "Интернет-банк", "Система, предоставляющая онлайн-обслуживание")
System(website, "Сайт", "Интерфейс, предоставляющий клиентам первичное офлайн-обслуживание и маркетинговую информацию")
System_Ext(callCenterSystem, "Система кол-центра", "Система, предназначенная для обработки входящих звонков от клиентов")
System_Ext(smsGateway, "СМС-шлюз телеком-оператора", "Система, предназначенная для отправки СМС-сообщений")
System(s3storage, "S3-хранилище", "Внешнее хранилище, используемое для хранения файлов")


Rel(frontOfficeManager,abs,"Взаимодействует при предоставлении офлайн-обслуживания")
Rel(backOfficeManager,abs, "Взаимодействует при предоставлении онлайн-обслуживания")
Rel(customer,onlineBank,"Получает онлайн-обслуживание")
Rel(customer,frontOfficeManager,"Получает офлайн-обслуживание")
Rel(onlineBank,abs, "Взаимодействует при предоставлении онлайн-обслуживания")
Rel(callCenterManager,callCenterSystem, "Взаимодействует при предоставлении первичного офлайн-обслуживания, обрабатывая входящие звонки от клиентов")
Rel(customer,callCenterSystem, "Получает первичное офлайн-обслуживание, совершая звонки")
Rel(customer,website, "Получает первичное офлайн-обслуживание, заполняя веб-формы в браузере")
Rel(website,abs, "Взаимодействует при предоставлении первичного офлайн-обслуживания")
Rel(backOfficeManager,callCenterSystem, "Взаимодействует при предоставлении первичного офлайн-обслуживания, обрабатывая созданные менеджерами кол-центра заявки")
Rel(abs,smsGateway, "Отправляет СМС-уведомления")
Rel(smsGateway,customer,"Отправляет СМС-уведомления")
Rel(abs,s3storage,"Добавляет файлы с актуальными ставками")
Rel(callCenterSystem,s3storage,"Читает файлы с актуальными ставками")


@enduml
